version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: phygitals-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: phygitals_data
      MYSQL_USER: scraper
      MYSQL_PASSWORD: scraper-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-pw"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: phygitals-scraper
    depends_on:
      database:
        condition: service_healthy
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: phygitals_data
    volumes:
      - ./logs:/app/logs
    restart: "no"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: phygitals-webapp
    depends_on:
      database:
        condition: service_healthy
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DATABASE: phygitals_data
      FLASK_ENV: production
      FLASK_DEBUG: 0
    ports:
      - "5001:5001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/debug"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
